routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UsersController;
use App\Models\ModelBlog;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Landing Page
Route::get('/', function () {
    $data = ModelBlog::allData();

    return view('landing', compact('data'));
});

// Login
Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login.post');

// Admin Page
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/admin', [AdminController::class, 'index'])->name('admin');
    Route::resource('/admin/usermg', UsersController::class);
});

//bersama
Route::resource('/blog', BlogController::class);

//logout
Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');

resources/views/admin/usermg/create.blade.php
@extends('layouts.index')

@push('styles')

@endpush


@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="container">
                <form action="{{ route('usermg.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <br>
                    <div class="mb-3">
                        <label for="input_email" class="form-label">Nama</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class=" mb-3">
                        <label for="input_email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" required>
                    </div>
                    <div class="mb-3">
                        <label for="input_password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/usermg/index.blade.php
@extends('layouts.index')

@push('styles')

@endpush


@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
                <!--begin::User-->
                <div class="d-flex flex-column">
                    <!--begin::Name-->
                    <div class="d-flex align-items-center mb-2">
                        <h3>Data User</h3>
                    </div>
                    <!--end::Name-->
                </div>
                <!--end::User-->
                <!--begin::Actions-->
                <div class="d-flex my-4">
                    <a href="{{ route('usermg.create') }}" class="btn btn-sm btn-primary me-3"><i class="fas fa-add"></i> Tambah Data</a>
                </div>
                <!--end::Actions-->
            </div>
        </div>
        <div class="row">
            <div class="container">
                @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
                @endif
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Registered</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $user)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $user->name }}</td> <!-- Updated line -->
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->created_at }}</td>
                                <td>
                                    <form action="{{ route('usermg.destroy', $user->id) }}" method="POST" class="d-inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn" onclick="return confirm('Apakah Anda yakin ingin menghapus blog ini')"><i class="fas fa-trash text-danger"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection