routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UsersController;
use App\Models\ModelBlog;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Landing Page
Route::get('/', function () {
    $data = ModelBlog::allData();

    return view('landing', compact('data'));
});

// Login
Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login.post');

// Admin Page
Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/admin', [AdminController::class, 'index'])->name('admin');
    Route::resource('/admin/usermg', UsersController::class);
});

//bersama
Route::resource('/blog', BlogController::class);

//logout
Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\ModelBlog;
use App\Models\ModelKota;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = 'Blog';
        $data = ModelBlog::allData();

        return view('blog.index', compact('data', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = 'Tambah data Blog';
        $data = ModelKota::all();

        return view('blog.create', compact('data', 'title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'uploadgambar' => 'required',
            'masterkota' => 'required',
            'deskripsi' => ''
        ]);
        $document = $request->file('uploadgambar');
        $document_name = $document->getClientOriginalName();
        $doc_path = $document->store('public');

        $store = new ModelBlog();
        $store->nama_file = $document_name;
        $store->path_file = $doc_path;
        $store->deskripsi = $request->deskripsi;
        $store->reference = $request->masterkota;
        $store->save();

        return redirect()->route('blog.index')->with('success', 'Blog created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $blog
     * @return \Illuminate\Http\Response
     */
    public function show($blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit($blog)
    {
        $title = 'Edit data Blog';
        $data = ModelKota::all();
        $now = ModelBlog::findOrFail($blog);
        $idkota = $now->reference;
        $namakota = DB::table('master_kota')->select('nama_kota')->where('id_master_kota', $idkota)->value('nama_kota');

        return view('blog.edit', compact('data', 'title', 'now', 'namakota', 'blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $blog
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $blog)
    {

        $request->validate([
            'uploadgambar' => 'required',
            'masterkota' => 'required',
            'deskripsi' => ''
        ]);
        $document = $request->file('uploadgambar');
        $document_name = $document->getClientOriginalName();
        $doc_path = $document->store('public');

        $update = ModelBlog::where('id_blog', $blog)->firstOrFail();
        $update->nama_file = $document_name;
        $update->path_file = $doc_path;
        $update->deskripsi = $request->deskripsi;
        $update->reference = $request->masterkota;
        $update->save();

        return redirect()->route('blog.index')->with('success', 'Blog updated successfully');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy($blog)
    {
        $data = ModelBlog::findOrFail($blog);

        $data->delete();

        return redirect()->route('blog.index')->with('success', 'Blog deleted successfully');
    }
}

resources/views/blog/create.blade.php
@extends('layouts.index')

@push('styles')

@endpush


@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="container">
                <form action="{{ route('blog.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                        <label for="uploadgambar" class="form-label">Upload gambar kota</label><span class="text-danger">*</span>
                        <input class="form-control" type="file" id="uploadgambar" name="uploadgambar" required>
                    </div>
                    <br>
                    <div class="mb-3">
                        <label for="masterkota">Pilih kota</label><span class="text-danger">*</span>
                        <select class="form-select" id="masterkota" name="masterkota" aria-label="Default select example" required>
                            <option disabled selected>Pilih disini...</option>
                            @foreach($data as $item)
                            <option value="{{ $item->id_master_kota }}">{{ $item->nama_kota }}</option>
                            @endforeach
                        </select>
                    </div>
                    <br>
                    <div class="mb-3">
                        <div class="form-floating">
                            <input class="form-control" type="text" placeholder="edit" id="deskripsi" name="deskripsi" aria-label="default input example">
                            <label for="deksripsi">Deskripsi</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/blog/edit.blade.php
@extends('layouts.index')

@push('styles')

@endpush

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="container">
                <form action="{{ route('blog.update', $blog) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <label for="uploadgambar" class="form-label">Upload gambar kota</label><span class="text-danger">*</span>
                        <input class="form-control" type="file" id="uploadgambar" name="uploadgambar" required>
                    </div>
                    <br>
                    <div class="mb-3">
                        <label for="masterkota">Pilih kota</label><span class="text-danger">*</span>
                        <select class="form-select" id="masterkota" name="masterkota" aria-label="Default select example" required>
                            <option disabled selected>{{ $namakota }}</option>
                            @foreach($data as $item)
                            <option value="{{ $item->id_master_kota }}">{{ $item->nama_kota }}</option>
                            @endforeach
                        </select>
                    </div>
                    <br>
                    <div class="mb-3">
                        <div class="form-floating">
                            <input class="form-control" type="text" placeholder="edit" value="{{ $now->deskripsi }}" id="deskripsi" name="deskripsi" aria-label="default input example">
                            <label for="deskripsi">Deskripsi</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/blog/index.blade.php
@extends('layouts.index')

@push('styles')

@endpush


@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
                <!--begin::User-->
                <div class="d-flex flex-column">
                    <!--begin::Name-->
                    <div class="d-flex align-items-center mb-2">
                        <h3>Data dari table Blog</h3>
                    </div>
                    <!--end::Name-->
                </div>
                <!--end::User-->
                <!--begin::Actions-->
                <div class="d-flex my-4">
                    <a href="{{url('blog/create')}}" class="btn btn-sm btn-primary me-3"><i class="fas fa-add"></i> Tambah Data</a>
                </div>
                <!--end::Actions-->
            </div>
        </div>
        <div class="row">
            <div class="container">
                @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
                @endif
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Kota</th>
                                <th>Nama File</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $blog)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $blog->nama_kota }}</td> <!-- Updated line -->
                                <td>{{ $blog->nama_file }}</td>
                                <td>{{ $blog->deskripsi }}</td>
                                <td>
                                    <a href="{{ url('/storage/'.$blog->path_file)}}" class="me-3"><i class="fas fa-eye text-primary"></i></a>
                                    <a href="{{route('blog.edit', $blog->id_blog)}}" class="me-3"><i class="fas fa-pencil text-success"></i></a>
                                    <form action="{{ route('blog.destroy', $blog->id_blog) }}" method="POST" class="d-inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn" onclick="return confirm('Apakah Anda yakin ingin menghapus blog ini')"><i class="fas fa-trash text-danger"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection